name: pml_ship
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.0
  intl: ^0.18.0
  pin_code_fields: ^8.0.1
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  sizer: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
    - family: Jost
      fonts:
        - asset: assets/fonts/JostRomanRegular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSansRomanRegular.ttf
          weight: 400
