name: pml_ship
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  device_info_plus: ^10.1.0
  dotted_border: ^2.1.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_otp_text_field: ^1.1.3+2
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  http: ^1.2.2
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/logo/
    - assets/image/onboarding/
    - assets/image/payment/
    - assets/image/port/
    - assets/image/ship/
    - assets/icon/
    - assets/icon/weather/
    - assets/icon/weather/en/am/
    - assets/icon/weather/en/pm/
    - assets/icon/weather/id/am/
    - assets/icon/weather/id/pm/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
